import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import styles from "../../index.module.css";
import { trpc } from "../../../utils/trpc";

const NewMessage: NextPage = () => {
  const { mutate } = trpc.useMutation(["messages.addMessage"]);

  const [message, setMessage] = useState<null | string>(null);

  return (
    <>
      <Head>
        <title>Email Search Service</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.containerOuter}>
        <div className={styles.containerInner}>
          <h1 className={styles.title}>
            Email <span className={styles.titlePink}>Search</span> Service
          </h1>

          <textarea style={{whiteSpace: 'pre'}} onChange={(e) => setMessage(e.target.value)}></textarea>
          <button
            disabled={!message}
            onClick={() => {
              console.log(message);
              if (message) {
                mutate({ message });
              }
            }}
          >
            Submit
          </button>
        </div>
      </div>
    </>
  );
};

export default NewMessage;
